apiVersion: apps/v1
kind: Deployment
metadata:
  name: owlvey-bifrost-local-deployment
  namespace: owlvey
spec:
  replicas: 1
  selector:
    matchLabels:
      key: owlvey-bifrost-pod
  template:
    metadata:
      labels:
        key: owlvey-bifrost-pod
    spec:      
      containers:
      - name: owlvey-bifrost
        image: localhost:48700/owlvey/bifrost:latest
        imagePullPolicy: Always
        ports:
            - containerPort: 48702
              name: admin-port
            - containerPort: 48701
              name: listerner-port
        env:
            - name: "ENVIRONMENT"
              value: "k8s"
